"""TrendRadar 热度追踪 + 指纹参数。"""

HEAT_SLEEP_HOURS = 24
HEAT_DEEP_CYCLES = 3
HEAT_DEEP_SPAN = 12
HEAT_SUSTAINED_CYCLES = 2
HEAT_SUSTAINED_SPAN = 6

FINGERPRINT_MD5_LEN = 16
FINGERPRINT_URL_SEGMENTS = 3
FINGERPRINT_TITLE_TRUNCATE = 40
